title: raspberry-pi-command
hero_image: images/banner.png
description: raspberry-pi-command description
version: 4
listed: false
copyedit: false
last_tested: "2019-05-08"
steps:
  - title: Introduction
  - title: What is a command?
  - title: Create your own command
  - title: Add text effects
  - title: Challenge: Customise the command
  - title: Add to the menu
  - title: Create a desktop shortcut
