---
title: Create a new command on Raspberry Pi
hero_image: images/banner.png
description: Write a new Bash script that can be run as a command from a terminal
  window or the main menu
description: Write a new Bash script that can be run as a command from a terminal
  window or the main menu
version: 4
listed: true
copyedit: true
last_tested: '2019-05-08'
steps:
- title: What you will make
- title: What is a command?
- title: Create your own command
  completion:
  - engaged
- title: Add text effects
- title: 'Challenge: customise your command'
- title: Add to the menu
- title: More colours
  completion:
  - internal
- title: 'Challenge: create a new command'
  challenge: true
  completion:
  - external
- title: What can you do now?
